package com.example.zenith.entity;

public enum ActionType {
    TRANSFER_INITIATED, TRANSFER_COMPLETED, TRANSFER_FAILED,
    DEPOSIT_COMPLETED, DEPOSIT_FAILED,
    WITHDRAWAL_COMPLETED, WITHDRAWAL_FAILED,
    REVERSAL_COMPLETED, REVERSAL_FAILED,
    ACCOUNT_CREATED, SUSPICIOUS_ACTIVITY_FLAGGED,
    INTEREST_APPLIED, INTEREST_FAILED
}